export const data = [{
    "id": 1,
    "first_name": "Nikolia",
    "last_name": "O' Timony",
    "email": "notimony0@washingtonpost.com",
    "phone": "317-974-6911"
  }, {
    "id": 2,
    "first_name": "Karlee",
    "last_name": "Groll",
    "email": "kgroll1@zdnet.com",
    "phone": "630-504-7001"
  }, {
    "id": 3,
    "first_name": "Gal",
    "last_name": "Grigoli",
    "email": "ggrigoli2@paginegialle.it",
    "phone": "187-380-1570"
  }, {
    "id": 4,
    "first_name": "Kristel",
    "last_name": "Martinon",
    "email": "kmartinon3@ihg.com",
    "phone": "691-862-1287"
  }, {
    "id": 5,
    "first_name": "Carling",
    "last_name": "McLucky",
    "email": "cmclucky4@twitpic.com",
    "phone": "486-471-1078"
  }, {
    "id": 6,
    "first_name": "Larisa",
    "last_name": "Robroe",
    "email": "lrobroe5@bigcartel.com",
    "phone": "924-475-8104"
  }, {
    "id": 7,
    "first_name": "Nanice",
    "last_name": "Eam",
    "email": "neam6@prlog.org",
    "phone": "331-727-5541"
  }, {
    "id": 8,
    "first_name": "Olenka",
    "last_name": "Purcell",
    "email": "opurcell7@hud.gov",
    "phone": "620-968-5941"
  }, {
    "id": 9,
    "first_name": "Jason",
    "last_name": "Exeter",
    "email": "jexeter8@vkontakte.ru",
    "phone": "833-107-2555"
  }, {
    "id": 10,
    "first_name": "Colette",
    "last_name": "Goldthorp",
    "email": "cgoldthorp9@scribd.com",
    "phone": "661-356-3258"
  }, {
    "id": 11,
    "first_name": "Tedman",
    "last_name": "Pinchen",
    "email": "tpinchena@ifeng.com",
    "phone": "714-731-9271"
  }, {
    "id": 12,
    "first_name": "Jacenta",
    "last_name": "Janos",
    "email": "jjanosb@fema.gov",
    "phone": "429-555-5171"
  }, {
    "id": 13,
    "first_name": "Cornall",
    "last_name": "Cowap",
    "email": "ccowapc@opensource.org",
    "phone": "767-468-0940"
  }, {
    "id": 14,
    "first_name": "Leelah",
    "last_name": "Norquoy",
    "email": "lnorquoyd@mapy.cz",
    "phone": "426-464-4410"
  }, {
    "id": 15,
    "first_name": "Nada",
    "last_name": "Gilburt",
    "email": "ngilburte@apple.com",
    "phone": "132-737-7059"
  }, {
    "id": 16,
    "first_name": "Dasie",
    "last_name": "Patillo",
    "email": "dpatillof@smugmug.com",
    "phone": "356-519-8073"
  }, {
    "id": 17,
    "first_name": "Leigh",
    "last_name": "Laird-Craig",
    "email": "llairdcraigg@liveinternet.ru",
    "phone": "832-415-7257"
  }, {
    "id": 18,
    "first_name": "Norina",
    "last_name": "Athy",
    "email": "nathyh@cyberchimps.com",
    "phone": "321-510-4976"
  }, {
    "id": 19,
    "first_name": "Max",
    "last_name": "Stanfield",
    "email": "mstanfieldi@tuttocitta.it",
    "phone": "271-233-8816"
  }, {
    "id": 20,
    "first_name": "Ag",
    "last_name": "Dod",
    "email": "adodj@blogspot.com",
    "phone": "517-498-3120"
  }, {
    "id": 21,
    "first_name": "Dolli",
    "last_name": "Vatcher",
    "email": "dvatcherk@berkeley.edu",
    "phone": "861-580-9087"
  }, {
    "id": 22,
    "first_name": "Alisa",
    "last_name": "Evison",
    "email": "aevisonl@ucoz.ru",
    "phone": "180-680-1972"
  }, {
    "id": 23,
    "first_name": "Daniela",
    "last_name": "Blowes",
    "email": "dblowesm@sphinn.com",
    "phone": "378-246-4147"
  }, {
    "id": 24,
    "first_name": "Anatola",
    "last_name": "Maddy",
    "email": "amaddyn@accuweather.com",
    "phone": "275-403-6595"
  }, {
    "id": 25,
    "first_name": "Alexina",
    "last_name": "Tacker",
    "email": "atackero@list-manage.com",
    "phone": "567-797-0772"
  }, {
    "id": 26,
    "first_name": "Claretta",
    "last_name": "Bracher",
    "email": "cbracherp@blogtalkradio.com",
    "phone": "349-394-4027"
  }, {
    "id": 27,
    "first_name": "Ber",
    "last_name": "Bloomfield",
    "email": "bbloomfieldq@wufoo.com",
    "phone": "203-204-7024"
  }, {
    "id": 28,
    "first_name": "Shaylyn",
    "last_name": "Worswick",
    "email": "sworswickr@craigslist.org",
    "phone": "978-997-3624"
  }, {
    "id": 29,
    "first_name": "Efren",
    "last_name": "Rother",
    "email": "erothers@ibm.com",
    "phone": "876-617-7298"
  }, {
    "id": 30,
    "first_name": "Luce",
    "last_name": "Newsome",
    "email": "lnewsomet@sciencedaily.com",
    "phone": "211-620-7604"
  }, {
    "id": 31,
    "first_name": "Cloe",
    "last_name": "O'Geneay",
    "email": "cogeneayu@msn.com",
    "phone": "561-699-7847"
  }, {
    "id": 32,
    "first_name": "Gaby",
    "last_name": "Dubock",
    "email": "gdubockv@unblog.fr",
    "phone": "284-594-2717"
  }, {
    "id": 33,
    "first_name": "Cariotta",
    "last_name": "Klicher",
    "email": "cklicherw@howstuffworks.com",
    "phone": "708-614-4253"
  }, {
    "id": 34,
    "first_name": "Donella",
    "last_name": "Hambly",
    "email": "dhamblyx@cocolog-nifty.com",
    "phone": "422-176-8880"
  }, {
    "id": 35,
    "first_name": "Lisle",
    "last_name": "Bambrugh",
    "email": "lbambrughy@wikia.com",
    "phone": "996-242-1514"
  }, {
    "id": 36,
    "first_name": "Cassie",
    "last_name": "Rhule",
    "email": "crhulez@hao123.com",
    "phone": "983-957-6386"
  }, {
    "id": 37,
    "first_name": "Elfie",
    "last_name": "Hartup",
    "email": "ehartup10@narod.ru",
    "phone": "744-848-2026"
  }, {
    "id": 38,
    "first_name": "Judah",
    "last_name": "Dobel",
    "email": "jdobel11@dedecms.com",
    "phone": "804-976-8381"
  }, {
    "id": 39,
    "first_name": "Brose",
    "last_name": "Van Eeden",
    "email": "bvaneeden12@imdb.com",
    "phone": "890-971-8882"
  }, {
    "id": 40,
    "first_name": "Cash",
    "last_name": "Sailor",
    "email": "csailor13@diigo.com",
    "phone": "371-416-8947"
  }, {
    "id": 41,
    "first_name": "Paco",
    "last_name": "Face",
    "email": "pface14@marriott.com",
    "phone": "919-468-6147"
  }, {
    "id": 42,
    "first_name": "Ailene",
    "last_name": "Jollie",
    "email": "ajollie15@apple.com",
    "phone": "719-578-4216"
  }, {
    "id": 43,
    "first_name": "Dene",
    "last_name": "Symper",
    "email": "dsymper16@last.fm",
    "phone": "582-789-5393"
  }, {
    "id": 44,
    "first_name": "Jaynell",
    "last_name": "Bartolijn",
    "email": "jbartolijn17@bigcartel.com",
    "phone": "154-271-5187"
  }, {
    "id": 45,
    "first_name": "Jilli",
    "last_name": "Hadwen",
    "email": "jhadwen18@hatena.ne.jp",
    "phone": "164-553-5538"
  }, {
    "id": 46,
    "first_name": "Giraud",
    "last_name": "Curd",
    "email": "gcurd19@wikimedia.org",
    "phone": "520-952-2118"
  }, {
    "id": 47,
    "first_name": "Anatole",
    "last_name": "Bertelmot",
    "email": "abertelmot1a@elpais.com",
    "phone": "194-564-2446"
  }, {
    "id": 48,
    "first_name": "Helaina",
    "last_name": "Willowby",
    "email": "hwillowby1b@answers.com",
    "phone": "855-968-7846"
  }, {
    "id": 49,
    "first_name": "Philis",
    "last_name": "Gaymar",
    "email": "pgaymar1c@unc.edu",
    "phone": "660-523-2379"
  }, {
    "id": 50,
    "first_name": "Aeriela",
    "last_name": "Vagg",
    "email": "avagg1d@bluehost.com",
    "phone": "928-319-0223"
  }, {
    "id": 51,
    "first_name": "Ester",
    "last_name": "Oloshkin",
    "email": "eoloshkin1e@japanpost.jp",
    "phone": "249-905-3301"
  }, {
    "id": 52,
    "first_name": "Rozamond",
    "last_name": "Draper",
    "email": "rdraper1f@comsenz.com",
    "phone": "239-926-5540"
  }, {
    "id": 53,
    "first_name": "Dev",
    "last_name": "Wurz",
    "email": "dwurz1g@ovh.net",
    "phone": "890-280-0879"
  }, {
    "id": 54,
    "first_name": "Evangelina",
    "last_name": "Darington",
    "email": "edarington1h@facebook.com",
    "phone": "836-309-1453"
  }, {
    "id": 55,
    "first_name": "Kay",
    "last_name": "Campanelli",
    "email": "kcampanelli1i@tiny.cc",
    "phone": "591-763-4821"
  }, {
    "id": 56,
    "first_name": "Hally",
    "last_name": "Strange",
    "email": "hstrange1j@istockphoto.com",
    "phone": "534-724-1117"
  }, {
    "id": 57,
    "first_name": "Gaby",
    "last_name": "Pyne",
    "email": "gpyne1k@about.com",
    "phone": "323-822-6746"
  }, {
    "id": 58,
    "first_name": "Melania",
    "last_name": "Coombes",
    "email": "mcoombes1l@marriott.com",
    "phone": "421-215-4603"
  }, {
    "id": 59,
    "first_name": "Elliot",
    "last_name": "Dumphry",
    "email": "edumphry1m@tripod.com",
    "phone": "849-493-3615"
  }, {
    "id": 60,
    "first_name": "Tam",
    "last_name": "Walklot",
    "email": "twalklot1n@amazon.co.uk",
    "phone": "345-187-1100"
  }, {
    "id": 61,
    "first_name": "Arly",
    "last_name": "Snailham",
    "email": "asnailham1o@businessinsider.com",
    "phone": "573-234-0529"
  }, {
    "id": 62,
    "first_name": "Bernette",
    "last_name": "Keenlyside",
    "email": "bkeenlyside1p@yandex.ru",
    "phone": "865-499-2822"
  }, {
    "id": 63,
    "first_name": "Talbert",
    "last_name": "Thursfield",
    "email": "tthursfield1q@icio.us",
    "phone": "725-786-6641"
  }, {
    "id": 64,
    "first_name": "Elihu",
    "last_name": "Kopman",
    "email": "ekopman1r@gnu.org",
    "phone": "191-390-4712"
  }, {
    "id": 65,
    "first_name": "Lucie",
    "last_name": "Dilland",
    "email": "ldilland1s@addthis.com",
    "phone": "236-392-1273"
  }, {
    "id": 66,
    "first_name": "Bjorn",
    "last_name": "Ferrone",
    "email": "bferrone1t@youtu.be",
    "phone": "911-280-8957"
  }, {
    "id": 67,
    "first_name": "Nickie",
    "last_name": "Speek",
    "email": "nspeek1u@msn.com",
    "phone": "982-476-5028"
  }, {
    "id": 68,
    "first_name": "Skelly",
    "last_name": "Reichhardt",
    "email": "sreichhardt1v@gizmodo.com",
    "phone": "615-264-8955"
  }, {
    "id": 69,
    "first_name": "Loni",
    "last_name": "Abramovici",
    "email": "labramovici1w@independent.co.uk",
    "phone": "756-962-3741"
  }, {
    "id": 70,
    "first_name": "Nanine",
    "last_name": "McMylor",
    "email": "nmcmylor1x@com.com",
    "phone": "645-104-1157"
  }, {
    "id": 71,
    "first_name": "Robbyn",
    "last_name": "Fidoe",
    "email": "rfidoe1y@php.net",
    "phone": "353-743-8311"
  }, {
    "id": 72,
    "first_name": "Dael",
    "last_name": "Renac",
    "email": "drenac1z@people.com.cn",
    "phone": "849-510-4408"
  }, {
    "id": 73,
    "first_name": "Kirk",
    "last_name": "Gearing",
    "email": "kgearing20@wsj.com",
    "phone": "485-803-2830"
  }, {
    "id": 74,
    "first_name": "Kane",
    "last_name": "Buche",
    "email": "kbuche21@odnoklassniki.ru",
    "phone": "418-997-5186"
  }, {
    "id": 75,
    "first_name": "Silvie",
    "last_name": "Preshous",
    "email": "spreshous22@flavors.me",
    "phone": "966-939-1410"
  }, {
    "id": 76,
    "first_name": "Karissa",
    "last_name": "Jerratsch",
    "email": "kjerratsch23@usda.gov",
    "phone": "781-629-3596"
  }, {
    "id": 77,
    "first_name": "Darsey",
    "last_name": "O'Grada",
    "email": "dograda24@hao123.com",
    "phone": "362-548-9134"
  }, {
    "id": 78,
    "first_name": "Nikolai",
    "last_name": "Persse",
    "email": "npersse25@blog.com",
    "phone": "356-893-3608"
  }, {
    "id": 79,
    "first_name": "Rance",
    "last_name": "Lindsay",
    "email": "rlindsay26@webmd.com",
    "phone": "627-623-1719"
  }, {
    "id": 80,
    "first_name": "Garret",
    "last_name": "Stansby",
    "email": "gstansby27@paypal.com",
    "phone": "276-904-6872"
  }, {
    "id": 81,
    "first_name": "Mark",
    "last_name": "Lippard",
    "email": "mlippard28@istockphoto.com",
    "phone": "679-183-5702"
  }, {
    "id": 82,
    "first_name": "Lorin",
    "last_name": "Test",
    "email": "ltest29@whitehouse.gov",
    "phone": "122-853-4151"
  }, {
    "id": 83,
    "first_name": "Jacqui",
    "last_name": "Barhams",
    "email": "jbarhams2a@ucoz.com",
    "phone": "171-489-6698"
  }, {
    "id": 84,
    "first_name": "Pierson",
    "last_name": "McVey",
    "email": "pmcvey2b@bluehost.com",
    "phone": "542-659-1833"
  }, {
    "id": 85,
    "first_name": "Evin",
    "last_name": "Kenaway",
    "email": "ekenaway2c@nasa.gov",
    "phone": "227-942-4734"
  }, {
    "id": 86,
    "first_name": "Marshal",
    "last_name": "Chappell",
    "email": "mchappell2d@yolasite.com",
    "phone": "813-869-4862"
  }, {
    "id": 87,
    "first_name": "Chandal",
    "last_name": "Vockins",
    "email": "cvockins2e@paypal.com",
    "phone": "609-351-0399"
  }, {
    "id": 88,
    "first_name": "Katharina",
    "last_name": "Rubinshtein",
    "email": "krubinshtein2f@pen.io",
    "phone": "914-343-4970"
  }, {
    "id": 89,
    "first_name": "Glyn",
    "last_name": "Naper",
    "email": "gnaper2g@yolasite.com",
    "phone": "918-161-0125"
  }, {
    "id": 90,
    "first_name": "Alfonso",
    "last_name": "Fawkes",
    "email": "afawkes2h@purevolume.com",
    "phone": "704-180-4958"
  }, {
    "id": 91,
    "first_name": "Nicol",
    "last_name": "Leasor",
    "email": "nleasor2i@dell.com",
    "phone": "888-646-4013"
  }, {
    "id": 92,
    "first_name": "Nalani",
    "last_name": "Cottey",
    "email": "ncottey2j@hubpages.com",
    "phone": "945-662-0886"
  }, {
    "id": 93,
    "first_name": "Bernette",
    "last_name": "Nelissen",
    "email": "bnelissen2k@state.gov",
    "phone": "116-550-6152"
  }, {
    "id": 94,
    "first_name": "Rogers",
    "last_name": "Friday",
    "email": "rfriday2l@opensource.org",
    "phone": "562-485-2192"
  }, {
    "id": 95,
    "first_name": "Mikel",
    "last_name": "Daltrey",
    "email": "mdaltrey2m@behance.net",
    "phone": "655-591-0591"
  }, {
    "id": 96,
    "first_name": "Quentin",
    "last_name": "Raund",
    "email": "qraund2n@yellowbook.com",
    "phone": "550-542-7895"
  }, {
    "id": 97,
    "first_name": "Ronnie",
    "last_name": "Charlton",
    "email": "rcharlton2o@networkadvertising.org",
    "phone": "225-693-4417"
  }, {
    "id": 98,
    "first_name": "Lothaire",
    "last_name": "Hudghton",
    "email": "lhudghton2p@google.co.jp",
    "phone": "813-167-3501"
  }, {
    "id": 99,
    "first_name": "Tabbatha",
    "last_name": "Milvarnie",
    "email": "tmilvarnie2q@newsvine.com",
    "phone": "626-220-4184"
  }, {
    "id": 100,
    "first_name": "Antonetta",
    "last_name": "Nisbith",
    "email": "anisbith2r@theglobeandmail.com",
    "phone": "209-429-3190"
  }]

  export const columns = [
    {
      title: 'First Name',
      dataIndex: 'first_name',
      key: 'firstname',
    },
    {
      title: 'Last Name',
      dataIndex: 'last_name',
      key: 'lastname',
    },
    {
      title: 'E-Mail',
      dataIndex: 'email',
      key: 'email',
    },
    {
        title: 'Phone No',
        dataIndex: 'phone',
        key: 'phone',
    },
  ];